### ISSUE TITLE
How do we pull the threads information/monitor like tm1 top

### ISSUE THREAD

**Issue by vpkumarbi** [cubewise-code/TM1py-samples#10]
We upgraded to PA 11.6,  any suggestion on how to pull the wait threads and kill or instead pull all threads and their info

**Comment by MariusWirtz** [comment]
TM1py allows you to query or cancel running threads.
Here is an example that cancels threads that run the Bedrock.Server.Wait process:
```
from TM1py.Services import TM1Service

# Connect to TM1
with TM1Service(address='localhost', port=12354, user='admin', password='apple', ssl=True) as tm1:
    # Get all running threads
    threads = tm1.monitoring.get_threads()

    # Prints all running threads with their properties:
    print(threads)

    # Find thread that runs the Bedrock.Server.Wait Process and cancel it
    for thread in threads:
        if thread['ObjectName'] == 'Bedrock.Server.Wait':
            tm1.monitoring.cancel_thread(thread['ID'])
```

**Comment by cubewise-tryan** [comment]
Hi @vpkumarbi,

If you need to see what is happening in TM1 or want to cancel or disconnect users you can use our product [Pulse for TM1](https://code.cubewise.com/pulse-overview/). 

We have also just released another utility that can cancel and disconnect users using TM1's C API: https://github.com/cubewise-code/tm1kill

**Comment by vpkumarbi** [comment]
@MariusWirtz  i can kill an active thread, to kill just a wait thread (by just looking at the status of the thread, instead of object name) and send an email/notification is there a service already?

**Comment by vpkumarbi** [comment]
@cubewise-tryan  will try

**Comment by MariusWirtz** [comment]
Yes. You can use TM1py to kill waiting threads in TM1.
TM1py is only a wrapper around the TM1 REST API. It doesn't do stuff like sending mails.

**Comment by rclapp** [comment]
Any suggestions on how to convert the weird Elapsed Time formats to seconds? "Any one else think "P0DT00H00M00S" is a very odd time format

**Comment by rclapp** [comment]
Figured it our if anyone else wants to know datetime.datetime.strptime(self.ElapsedTime, "P0DT%HH%MM%SS").time()

**Comment by jbeanz23** [comment]
hi @rclapp 
Where did you stick this? I am query threads to kill, like below.  Where would you format the time?
Thanks

# Connect to TM1
with TM1Service(**config["tm1srv02"]) as tm1:
    # Get all running threads
    threads = tm1.monitoring.get_threads()

    # Prints all running threads with their properties:
    print(threads)

    # Find thread that runs the Bedrock.Server.Wait Process and cancel it
    for thread in threads:
        if thread['ObjectName'] == 'zks56500 Driver':
            #print(thread)
            tm1.monitoring.cancel_thread(thread['ID'])
