### ISSUE TITLE
How can I put cell to cube

### ISSUE THREAD

**Issue by l61224** [cubewise-code/TM1py-samples#20]
I try to put cell to a cube but I get some trouble.
How can I fix it?   
Or there are other ways to do without using view?   Thanks.

# In[ ]:
import quandl
import math
from TM1py.Services import TM1Service

import quandl
from TM1py.Services import TM1Service

#load Stock data for IBM
data = quandl.get("WIKI/IBM", start_date='2015-01-02', end_date='2015-01-02')

#create cellset from raw data
cube = 'C_StockPrices'
measures = ('Open', 'High', 'Low', 'Close', 'Volume', 'Adj. Open', 'Adj. High', 'Adj. Low', 'Adj. Close', 'Adj. Volume')
cellset = {}
for tmstp, row in data.iterrows():
　date = tmstp.date()
　for measure in measures:
　　cellset[('WIKI', str(date), measure)] = row[measure]

#push data to TM1
with TM1Service(address='localhost', port=8002, user='admin', password='', ssl=False) as tm1:
　tm1.cubes.cells.write_values(cube, cellset)

# Out[ ]:
TM1pyException                            Traceback (most recent call last)
<ipython-input-32-ec98ac048906> in <module>()
　16 # push data to TM1
　17 with TM1Service(address='localhost', port=8002, user='admin', password='', ssl=False) as tm1:
---> 18     tm1.cubes.cells.write_values(cube, cellset)

c:\users\jacky.lai\python36\lib\site-packages\TM1py\Services\CellService.py in write_values(self, cube_name, cellset_as_dict, dimensions)
　109             updates.append(json.dumps(body_as_dict, ensure_ascii=False))
　110         updates = '[' + ','.join(updates) + ']'
--> 111         self._rest.POST(request=request, data=updates)
　112 
　113     def write_values_through_cellset(self, mdx, values):

c:\users\jacky.lai\python36\lib\site-packages\TM1py\Services\RESTService.py in wrapper(self, request, data)
　27         response = func(self, request, data)
　28         # Verify
---> 29         self.verify_response(response=response)
　30         return response
     31     return wrapper

c:\users\jacky.lai\python36\lib\site-packages\TM1py\Services\RESTService.py in verify_response(response)
　201         """
　202         if not response.ok:
--> 203             raise TM1pyException(response.text, status_code=response.status_code, reason=response.reason)
　204 
　205     @staticmethod

# TM1pyException: Text: {"error":{"code":"500","message":"Invalid number of dimensions specified."}} Status Code: 400 Reason: Bad Request

**Comment by MariusWirtz** [comment]
Hi,
judging from the Error message, it looks like the cube C_StockPrices is not three dimensional.

If you run the `sample setup.py` and the `stock prices to cube.py` samples, does it through errors too?

**Comment by l61224** [comment]
Yes! I got the answer. Thank for your Reply.

I have the other problem:

I have already got elements from # A cube , 
the type of element is # <class 'TM1py.Utils.Utils.CaseAndSpaceInsensitiveTuplesDict'> .

If I want to put these elements to # B cube , how to transform the type of elements into  Dictionary?
Thank you for your patience

**Comment by MariusWirtz** [comment]
I understand that you want to transfer data from cube A to cube B.
Short answer:
Here is a sample do it with MDX
https://github.com/cubewise-code/TM1py-samples/blob/master/Load%20Data/cube%20to%20cube.py

Long answer:
When you query data from a cube, through either a cubeview or an MDX Query, TM1py will give you an instance of CaseAndSpaceInsensitiveTuplesDict.
It is a dictionary, with the special characteristic, that the keys (the element-unique-names of the coordinates) are neither case nor space sensitive (as you would expect coming from TM1).
See:
https://github.com/cubewise-code/TM1py-samples/blob/master/Query%20Data/query%20data%20through%20mdx.py

If you want to have a classic dictionary instead, you can convert the returned object with the dict() function:
`dict(content)`

Does that help you?

P.S. you can use the `build_pandas_dataframe_from_cellset` function to convert a cellset (the object that is being returned from a cubeview- or mdx-execution) into a pandas dataframe. This can be really handy if you want to manipulate (or analyse) data in python.
https://github.com/cubewise-code/TM1py-samples/blob/master/Query%20Data/cube%20data%20into%20pandas%20dataframe.py

**Comment by l61224** [comment]
Thank for your Reply.
I did try by these two ways but I still have some problem.

1.In Short answer:
I did it like the sample but the difference was these two cubes at the _same Instance_.
This is the report:
**ConnectionError:** HTTPConnectionPool(host='localhost', port=8002): Max retries exceeded with url: /api/v1/Configuration/ProductVersion/$value (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0A00A210>: Failed to establish a new connection: [WinError 10061] 無法連線，因為目標電腦拒絕連線。',))

After I do this then I will lose connection from my Instance.

2.In Long answer:
After I use the dict() function . It's still incorrect number of dimensions caused I can't put these to the other cube.
I did try some ways to do:
1) dataframe to dictionary ,
2) string to dictionary,
3) dataframe to array to dict
I still can't do the correct dictionary to put into the other cube :(

Thank you for your patience.

**Comment by MariusWirtz** [comment]
I think it would be easier if you just post your code here

**Comment by l61224** [comment]
I got the solution by using some loops,this is code:

Cube_name="C_Rate"
View_name="View_Test"

from TM1py.Services import TM1Service
import pandas as pd
from TM1py.Utils import Utils

#Get value for Source Cube
with TM1Service(address='localhost', port=8002, user='admin', password='', ssl=False) as tm1:
    content = tm1.cubes.cells.get_view_content(cube_name=Cube_name, view_name=View_name, private=False)
    dcontent = Utils.build_pandas_dataframe_from_cellset(content, multiindex=False)

#Get Element&Value
dict_dcontent=dict(dcontent)
Elements=[]
Values=[]
for i in dict_dcontent.values():
    tmp_value=dict(i)
    for i in tmp_value.values():
        if type(i) is str:
            Elements.append(i)
        else:
            Values.append(i)

#Do a dictionary            
Element1=Elements[0:2]
Element2=Elements[2:4]
Elements=zip(Element1,Element2)
Keys=list(Elements)

dict_Test={}
for i in range(0,len(Keys)):
    dict_Test[Keys[i]]=Values[i]
#print(dict_Test)

#Put into Target Cube
with TM1Service(address='localhost',port=8002,user='admin',password='',ssl=False) as tm1:
    tm1.cubes.cells.write_values("C_Rate2",dict_Test)

Thank you for your patience.

**Comment by MariusWirtz** [comment]
Happy to hear that you found a solution!
