### ISSUE TITLE
chores

### ISSUE THREAD

**Issue by abhijit2813** [cubewise-code/TM1py-samples#24]
After executing below code
    # Read Chore:
    c = tm1.chores.get('aaa')

    # Print out the tasks
    for task in c.tasks:
        print("Process: {} Parameters: {}".format(task, task.parameters))

I am facing error as
Text: {"error":{"code":"","message":"'Chores' resource can not be resolved on type 'EntityContainer'."}} Status Code: 404 Reason: Not Found

how to resolve it?
Thanks in advance

**Comment by MariusWirtz** [comment]
What’s your version of TM1 / Planning Analytics?

**Comment by abhijit2813** [comment]
TM1 10.2.2

**Comment by MariusWirtz** [comment]
https://code.cubewise.com/blog/determine-the-version-of-ibm-planning-analytics

**Comment by abhijit2813** [comment]
10.2.20000.50159

**Comment by MariusWirtz** [comment]
Version is too old. REST API in that version is very limited.

You need to have 10.2.2 FP 5 or higher.

**Comment by abhijit2813** [comment]
Ok  I am downloading FP5 fixpack and then I will checks
once again thanks Marius for your prompt support.

**Comment by MariusWirtz** [comment]
Maybe upgrade to FP7. Then you can use all features of TM1py.
