### ISSUE TITLE
extracting alias from tm1 using tm1py

### ISSUE THREAD

**Issue by an5ir** [cubewise-code/TM1py-samples#28]
i am using TM1py to extract views from from tm1 cubes using python language.  However,  the alias of each dimension or element  of the view does not come along with each extraction. is there some way to get the alias with each extraction from tm1 ?

**Comment by MariusWirtz** [comment]
Hi,

the default execute_view function doesn't return the element alias, even when it is switched-on in the subset that is part of the view.

If you need the element attributes, you can use the execute_view_raw method instead. It gives you more flexibility, in a way that you can ask explicitly for certein attributes or member / element properties, however this function returns you the data in the raw format how the TM1 REST API returns it to python.  
Here is a sample:
```

with TM1Service(address="localhost", port=12354, user="admin", password="apple", ssl=True) as tm1:

    cube_name = "Plan_BudgetPlan"
    view_name = "Budget Input Total"

    data = tm1.cubes.cells.execute_view_raw(
        cube_name=cube_name,
        view_name=view_name,
        member_properties=["Name", "Attributes/AccountName"],
        private=False)

    print(data)
```

Other solutions would be:
- Query the Alias values separately
- Use MDX, to query data from TM1. In MDX you can request the Alias attributes that you need together with the data from the cube in a single Query.

Does that solve your problem?

**Comment by an5ir** [comment]
Hi, thanks for getting back to me.

can you give me an example of how can i use MDX string  to request Alias attributives with the data from the cube in a singe Query?  
thanks

**Comment by MariusWirtz** [comment]
```
with TM1Service(address='localhost', port=9699, user='admin', password='apple', ssl=False) as tm1:
    mdx = """
    WITH MEMBER [Bike Shares Measure].[Population] AS [}ElementAttributes_City].([}ElementAttributes_City].[Population])
    SELECT 
    NON EMPTY {[Date].Members}*{TM1SubsetAll([City])} ON ROWS, 
    NON EMPTY {[Bike Shares Measure].[Count], [Bike Shares Measure].[Population] } ON COLUMNS 
    FROM [Bike Shares] 
    WHERE ([Version].[Actual],[Bike Shares Measure].[Count])"""

    data = tm1.cubes.cells.execute_mdx(mdx)
    df = build_pandas_dataframe_from_cellset(data, multiindex=False)
    print(df)

```

**Comment by himanshu1922** [comment]
Hi @MariusWirtz 
I am facing a similar issue in which I need to extract member properties of }ElementAttributes_}Clients and }clientgroups of the user pin (9999 format) using python. Can you please suggest how can I achieve this.

**Comment by MariusWirtz** [comment]
Hi @himanshu1922,

Just do an MDX query against the `}ElementAttributes_}Cliente` cube and the `}clientgroups` cube

**Comment by himanshu1922** [comment]
Thanks Marius Wirtz.
