### ISSUE TITLE
extract alias from dimension hierarchy 

### ISSUE THREAD

**Issue by an5ir** [cubewise-code/TM1py-samples#29]
Hi, 
I am doing the following:

    with TM1Services(address = os.environ.get('address'), port = os.environ.get('port'), user = 
    os.environ.get('user'), password = os.environ.get('password'), ssl = False) as tm1:

        dimension = tm1.dimensions.get('product')
        hierarchy = dimension.hierarchies[0]

Is there a way to extract the code and name(so the code and it alias) of each element on the dimensional hierarchy  and what level of the hierarchy it is on?

**Comment by MariusWirtz** [comment]
Hi,

I would do it through MDX:
```

from TM1py.Services import TM1Service
from TM1py.Utils import Utils

with TM1Service(address='localhost', port=9699, user='admin', password='apple', ssl=False, logging=False) as tm1:
    mdx = """
    WITH 
    MEMBER [}ElementAttributes_Date].[Level] AS [Date].CurrentMember.Properties('LEVEL_NUMBER')    
    SELECT 
    {TM1SubsetAll([Date])} on ROWS, 
    {[}ElementAttributes_Date].[Alias], [}ElementAttributes_Date].[Level]} on COLUMNS  
    FROM [}ElementAttributes_Date] 
    """
    data = tm1.cubes.cells.execute_mdx(mdx)
    df = Utils.build_pandas_dataframe_from_cellset(data, multiindex=False)
    print(df)
```

Only downside of this approach is that it counts the Levels according to the MDX standard, which is: top down, while normally in TM1 Levels are counted bottom up

Cheers,

Marius

**Comment by lotsaram** [comment]
> Only downside of this approach is that it counts the Levels according to the MDX standard, which is: top down, while normally in TM1 Levels are counted bottom up
Well that **has** always been the way TM1 has treated levels but PA is moving to the MDX standard. If you look at the hierarchy levels in PAW "Level 0" indicates the top node. This is also how the hierarchies are supposed to be set in }HierarchyProperties.
If you wanted to return the TM1 level number you could use exactly the same approach, just create an attribute (i.e. a custom property) and populate it using a rule with the ELLEV function.
