### ISSUE TITLE
Alias extraction

### ISSUE THREAD

**Issue by an5ir** [cubewise-code/tm1py-samples#31]
Is there a way to extract the alias of a dimension when using mdx  quay to extract a view?

    with TM1Service(address='localhost', port=9611, user='admin', password='apple', ssl=True) as tm1:
        mdx = """
        SELECT 
        {
        [Date].[2017-01]:[Date].[2017-12]} on COLUMNS, 
        TM1DRILLDOWNMEMBER(  {[product].[001]},  ALL,  RECURSIVE ) on ROWS  
        FROM [Bike Shares] 
        WHERE ([Bike Shares Measure].[Count],[Version].[Actual]) 
      """

        data = tm1.cubes.cells.execute_mdx_raw(mdx)
        df = Utils.build_pandas_dataframe_from_cellset(data, multiindex=False)

**Comment by MariusWirtz** [comment]
Here is a sample:

```
with TM1Service(address='localhost', port=9699, user='admin', password='apple', ssl=False) as tm1:
    mdx = """
    WITH MEMBER [Bike Shares Measure].[City Alias] AS [}ElementAttributes_City].([}ElementAttributes_City].[City Alias])
    SELECT 
    NON EMPTY {[Date].Members}*{TM1SubsetAll([City])} ON ROWS, 
    NON EMPTY {[Bike Shares Measure].[Count], [Bike Shares Measure].[City Alias] } ON COLUMNS 
    FROM [Bike Shares] 
    WHERE ([Version].[Actual],[Bike Shares Measure].[Count])"""

    data = tm1.cubes.cells.execute_mdx(mdx)
    df = build_pandas_dataframe_from_cellset(data, multiindex=False)
    print(df)
```

**Comment by an5ir** [comment]
Hi sorry for getting back to you so late, i have tried:
    with TM1Service(address='localhost', port=9699, user='admin', password='apple', ssl=False) as tm1:
    mdx = """
    WITH MEMBER [Bike Shares Measure].[City Alias] AS [bike shares Measure].([bike shares Measure].[City Alias])
    SELECT 
    NON EMPTY {[Date].Members}} ON ROWS, 
    NON EMPTY {[Bike Shares Measure].[Count], [Bike Shares Measure].[City Alias] } ON COLUMNS 
    FROM [Bike Shares] 
    WHERE ([Version].[Actual],[Bike Shares Measure].[Count])"""

    data = tm1.cubes.cells.execute_mdx(mdx)
    df = build_pandas_dataframe_from_cellset(data, multiindex=False)
    print(df)

but it just return me status Code:400 Reason: Bad Request 

i have also tried:
    with TM1Service(address='localhost', port=9699, user='admin', password='apple', ssl=False) as tm1:
    mdx = """
    WITH MEMBER [Bike Shares Measure].[City Alias] AS [bike shares Measure].[bike shares Measure].[City Alias]
    SELECT 
    NON EMPTY {[Date].Members}} ON ROWS, 
    NON EMPTY {[Bike Shares Measure].[Count], [Bike Shares Measure].[City Alias] } ON COLUMNS 
    FROM [Bike Shares] 
    WHERE ([Version].[Actual],[Bike Shares Measure].[Count])"""

    data = tm1.cubes.cells.execute_mdx(mdx)
    df = build_pandas_dataframe_from_cellset(data, multiindex=False)
    print(df)
this return a dataframe but # error recursion in the values columns 

if  i do:
    with TM1Service(address='localhost', port=9699, user='admin', password='apple', ssl=False) as tm1:
    mdx = """
    WITH MEMBER [Bike Shares Measure].[City Alias] AS [bike shares Measure].[ElementAttributes_City].[City Alias]
    SELECT 
    NON EMPTY {[Date].Members}} ON ROWS, 
    NON EMPTY {[Bike Shares Measure].[Count], [Bike Shares Measure].[City Alias] } ON COLUMNS 
    FROM [Bike Shares] 
    WHERE ([Version].[Actual],[Bike Shares Measure].[Count])"""

    data = tm1.cubes.cells.execute_mdx(mdx)
    df = build_pandas_dataframe_from_cellset(data, multiindex=False)
    print(df)
same problem. what exactly do you mean by element attribute. is there any way to check for them?

**Comment by MariusWirtz** [comment]
Hi,


regarding 1,
in this case "400 Bad request" means that the MDX was invalid or maybe you are referencing cubes or dimensions that don't exist in the model.

regarding 2,
I have not seen "# error recursion" before as a value in a cell. 
Probably you are doing something wrong in the Query. 

regarding 3,
What do I mean by **element attribute**? This:

![image](https://user-images.githubusercontent.com/15182131/45712164-e6b0e100-bb8b-11e8-8ca1-a1cbfc73c2f3.png)

You can look at the attributes in Architect / Perspectives , or you can do it with TM1py:

```
from TM1py import TM1Service

with TM1Service(address='localhost', port=12354, user='admin', password='apple', ssl=True) as tm1:
    hierarchy = tm1.dimensions.hierarchies.get(
        dimension_name="plan_business_unit",
        hierarchy_name="plan_business_unit")
    attributes = hierarchy.element_attributes
    for attribute in attributes:
        print(attribute.name)

```

**Comment by an5ir** [comment]
if i did the following:
from TM1py import TM1Service

with TM1Service(address='localhost', port=12354, user='admin', password='apple', ssl=True) as tm1:
    hierarchy = tm1.dimensions.hierarchies.get(
        dimension_name="plan_business_unit",
        hierarchy_name="plan_business_unit")
    attributes = hierarchy.element_attributes
    for attribute in attributes:
        print(attribute.name)

and one of the attributes is 
Code and name

i tried running the following:
      with TM1Service(address='localhost', port=9699, user='admin', password='apple', ssl=False) as tm1:
        mdx = """
       WITH MEMBER [plan_business_unit].[plan_business_unit_Alias] AS [Code and Name]. 
      [plan_business_unit_Alias]
      SELECT 
      NON EMPTY {[Date].Members}} ON ROWS, 
      NON EMPTY {[plan_business_unit].[plan_business_unit_Alias]} ON COLUMNS 
      FROM [Bike Shares] 
      """

     data = tm1.cubes.cells.execute_mdx(mdx)
     df = build_pandas_dataframe_from_cellset(data, multiindex=False)
     print(df)
it outputs a dataframe but in the last column it said "Code and Name":  object not found


i have tried:
   with TM1Service(address='localhost', port=9699, user='admin', password='apple', ssl=False) as tm1:
        mdx = """
       WITH MEMBER [plan_business_unit].[plan_business_unit_Alias] AS [Code and Name].([Code and Name].[plan_business_unit_Alias])
      SELECT 
      NON EMPTY {[Date].Members}} ON ROWS, 
      NON EMPTY {[plan_business_unit].[plan_business_unit_Alias]} ON COLUMNS 
      FROM [Bike Shares] 
      """

     data = tm1.cubes.cells.execute_mdx(mdx)
     df = build_pandas_dataframe_from_cellset(data, multiindex=False)
     print(df)


this output status code 400: bad request


i have tried:
   with TM1Service(address='localhost', port=9699, user='admin', password='apple', ssl=False) as tm1:
        mdx = """
       WITH MEMBER [plan_business_unit].[plan_business_unit_Alias] AS [}Code and Name].([}Code and Name].[plan_business_unit_Alias])
      SELECT 
      NON EMPTY {[Date].Members}} ON ROWS, 
      NON EMPTY {[plan_business_unit].[plan_business_unit_Alias]} ON COLUMNS 
      FROM [Bike Shares] 
      """

     data = tm1.cubes.cells.execute_mdx(mdx)
     df = build_pandas_dataframe_from_cellset(data, multiindex=False)
     print(df)
this also produces this output status code 400: bad request
not sure how to implement it correctly?

**Comment by MariusWirtz** [comment]
Here is an MDX Query that works against the Planning Sample model (it comes with the TM1 installation):
```

from TM1py import TM1Service
from TM1py.Utils import Utils

with TM1Service(address='localhost', port=12354, user='admin', password='apple', ssl=True, logging=False) as tm1:
    mdx = """
    WITH MEMBER [plan_time].[AccountClass] AS 
        [}ElementAttributes_plan_chart_of_accounts].([}ElementAttributes_plan_chart_of_accounts].[AccountClass])
    SELECT 
    NON EMPTY {TM1SubsetToSet([plan_chart_of_accounts],"Default")} on ROWS, 
    NON EMPTY { [plan_time].[Q1-2004], [plan_time].[Q2-2004], [plan_time].[Q3-2004], [plan_time].[Q4-2004], [plan_time].[AccountClass]} on COLUMNS  
    FROM [plan_budgetPlan] 
    WHERE ([plan_version].[FY 2004 Budget],[plan_business_unit].[10000],[plan_department].[1000],[plan_exchange_rates].[actual],[plan_source].[goal]) 
    """
    data = tm1.cubes.cells.execute_mdx(mdx)
    df = Utils.build_pandas_dataframe_from_cellset(data)

    print(df)

```

Now you need to adjust the query, so that it matches your Cube and dimensions.

Good luck
