### ISSUE TITLE
Attributes

### ISSUE THREAD

**Issue by TCucen** [cubewise-code/TM1py-samples#34]
Hi All,

Thanks for the code, just trying to use it now. 

I am having an issue about updating the existing attribute because couldn't find a function. 

And trying something like
 
      h.add_element(element_name=Code, element_type='Numeric')
      dimension.hierarchies(0).element(Code).element_attributes('Name', 'Alias') = BusinessName

is not working.

How can I update an existing attribute ? 

Cheers,

**Comment by MariusWirtz** [comment]
Hi,

the easiest way to update elementattribute values is through a classic cell update in the }ElementAttributes_ cube:

```
from TM1py import TM1Service

with TM1Service(address='12.77.18.11', port=12354, user='admin', password='apple', ssl=True) as tm1:
    coordinates_and_values = {
        ('2018-11-26', 'Month'): '11',
        ('2018-11-26', 'Year'): '2018'
    }

    tm1.cubes.cells.write_values(
        "}ElementAttributes_Date",
        coordinates_and_values
    )
```
