### ISSUE TITLE
Cant establish a connection 

### ISSUE THREAD

**Issue by girmax** [cubewise-code/tm1py-samples#36]
ConnectionError: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //srv45tm1:8881/api/v1/Configuration/ProductVersion/$value (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CCE7113C50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

**Comment by MariusWirtz** [comment]
Please post the python code too.
