### ISSUE TITLE
can i get into insights to TI Processes

### ISSUE THREAD

**Issue by Rnvksm** [cubewise-code/tm1py-samples#40]

**Comment by Rnvksm** [comment]
for example i want to know the name  "headcount" present in which processes it need to check in detail 
 is that possible using Tm1py
 please help me out

**Comment by MariusWirtz** [comment]
Hi,

generally when you want to get insights about your TM1 model, the best place to look at is [PulseForTM1](https://code.cubewise.com/blog/google-for-your-tm1-model)

If you are looking for a simple solution you can, of course, use TM1py to load all processes into python and then parse through their code tabs:

``` python
config = configparser.ConfigParser()
config.read(r'config.ini')

pattern = "sElem"

with TM1Service(**config['tm1srv01']) as tm1:
    processes = tm1.processes.get_all()
    for process in processes:
        if pattern in "".join([
                process.prolog_procedure,
                process.metadata_procedure,
                process.data_procedure,
                process.epilog_procedure]):
            print(process.name)

```
