### ISSUE TITLE
Connecting with a proxy

### ISSUE THREAD

**Issue by christianthieme** [cubewise-code/tm1py-samples#44]
Hello, 

I'm having an issue connecting and I'm not sure what the issue is. I've gone through all the other material and have tried everything and can't seem to find a solution. I have a hunch that it has to do with the single sign on. I was able to test a server without single sign on (but with a few other differences and was able to connect), but am struggling to connect to the servers with single sign on. Here is my code: 

from TM1py import TM1Service

with TM1Service(
        address='tm1test.time.com', 
        user='',   #i've left this as an empty string because we use SSO, but also tested with signin 
        password='' , #same
        port=31000, 
        namespace='Cognos 7',
        ssl=True, 
        gateway='http://C10TEST.time.com/ibmcognos/cgi-bin/cognosisapi.dll'
        ) as tm1:
   server_name = tm1.server.get_server_name()
print(server_name)

When I run this code I get: 
TM1pyException: Text:  Status Code: 401 Reason: Unauthorized

When I run the code with my credentials I get the error: 
Error: Incorrect padding

Can you help me figure out what is going on? Should I be placing the empty string after user and password or something else? Or do you think the issue is something else? 

Thank you for your help!

Best, 
Christian

**Comment by MariusWirtz** [comment]
Hi,

does it work when you provide `None`  instead of empty string for user and password ?
The CAM namespace is case senstitive. This could also be a problem.

**Comment by MariusWirtz** [comment]
For me it works with this `config.ini` file:

``` ini
[tm1srv04]
address=localhost
port=13254
user=
password=
namespace=CUBEWISE
gateway=http://localhost:80/ibmcognos/cgi-bin/cognos.cgi
ssl=True
```

**Comment by vviau** [comment]
Hi @christianthieme ,

What is your TM1 and TM1py version?

The gateway parameter is a new feature which is not available in the current release.

Cheers,

Vincent

**Comment by christianthieme** [comment]
Hi @vviau,

Thank you for the quick reply. I'm running TM1 version 10.2.2 FP5. I'm running TM1py version 1.2.1.

**Comment by christianthieme** [comment]
Hi @MariusWirtz , 

Thank you for the quick reply. I reconfigured my code to use the config file and am still getting the 401 code. How is this code collecting my credentials to pass to TM1? I tried entering my credentials and got the following errror: File "L:\Users\ccarl\AppData\Local\Continuum\anaconda3\lib\base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)

Error: Incorrect padding

I know the config file works because I ran it on a test server and it worked. The test server is running a newer version of security I think than the production servers. I'm just not sure what else to try or what else could be wrong. 

I also tried running the code with None in the user and password field and got : 
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 1: invalid start byte

Thanks

**Comment by christianthieme** [comment]
@MariusWirtz, 

I've been doing a lot of testing and research, and it looks like the crux of my problem is there is a governance software that sits on top of our Cognos Servers and is blocking my API calls (I work at a very large, international company). I've found a non-dynamic work around for the moment by clicking the CAMURI link in a browser and pulling down the CAMPassport cookie and feeding it into the token generating function in the RESTservices.py. I am able to authenticate using this method. 

Thanks for all your help during this process. 

Best, 
Christian

**Comment by MariusWirtz** [comment]
Happy to hear that you found a workaround !
If you have further questions on TM1py or enhancement requests just open an issue.

Cheers,
Marius
