### ISSUE TITLE
not able to extract cube data completely  by using pivot 

### ISSUE THREAD

**Issue by Rnvksm** [cubewise-code/tm1py-samples#46]
i'm using this service to extract cube data as pivot **execute_view_dataframe_pivot** 
attaching screenshot please find below

![pivot](https://user-images.githubusercontent.com/49037021/57521592-5a337880-733e-11e9-9180-1ddefe17f1d1.PNG)

code:
config=ConfigParser()
         config.read(r'D:\Program Files\Python37-32\Codes\configp.ini')
         with TM1Service(**config[self.v2]) as tm1:
             pivot=tm1.cubes.cells.execute_view_dataframe_pivot(cube_name=self.entry1.get(),view_name=self.entry2.get(),private=True)
             #pivot=tm1.cubes.cells.execute_view_dataframe_pivot(cube_name='Employee',view_name='Employeeview',private=True)
             print(pivot)

**Comment by vviau** [comment]
Hi @Rnvksm ,

What do you mean by "not able to extract data completely"? Are you getting any error message? Are you missing values in the export?

Cheers,

Vincent

**Comment by Rnvksm** [comment]
Missing some fields

Regards
Ram

**Comment by MariusWirtz** [comment]
The columns aren't actually missing, they are just not printed. Thats why you see the `...`

When you call the print method on a big dataframe pandas will by default not print out all columns.
The columns do exist though!

**Comment by Rnvksm** [comment]
If I want to see all data without ... What change need in code could you
please help me out

**Comment by MariusWirtz** [comment]
Please post general python or pandas questions that are unrelated to TM1py at [www.stackoverflow.com](www.stackoverflow.com)
