### ISSUE TITLE
Tm1 data need to plot

### ISSUE THREAD

**Issue by Rnvksm** [cubewise-code/tm1py-samples#47]
Can you provide some good example need to plot Tm1 data in Tm1py

**Comment by vviau** [comment]
Hi @Rnvksm ,

We published a series of articles around Data science with TM1 where we use Plotly with Jupiter Notebook to plot chart:
https://code.cubewise.com/blog/data-science-with-tm1-planning-analytics to 

I hope this help,

Cheers,

Vincent

**Comment by Rnvksm** [comment]
Thanks for your response,

Can you provide some different example
