### ISSUE TITLE
Links need updating

### ISSUE THREAD

**Issue by JDLovering** [cubewise-code/tm1py-samples#55]
Python/tm1py-samples-master/Samples/exploratory_analysis.ipynb
The two links are not working as below

The code requires an FX cube that contains data for 2017. You can run this **script** to set up the cube up in your TM1 model. In order to load the exchange rates into the cube run this **script** .

Not sure how to report these types of issues, let me know as I'll be going over the samples in next weeks.

James

**Comment by MariusWirtz** [comment]
Hi @JDLovering ,

thanks for the info. I fixed the broken links.

If you happen to find other issues, you can just open an issue here, or ideally if you can fix them yourself create a MR with the fix.

I hope the samples help to understand TM1py better!

Marius

**Comment by JDLovering** [comment]
Thanks
