### ISSUE TITLE
install TM1py error

### ISSUE THREAD

**Issue by slu18** [cubewise-code/tm1py-samples#56]
I follow tm1py install guide, download Anaconda, window, 3.7 version, launch Anaconda prompt, type pip install TM1py, I got "Could not find a version that satisfies the requirement TM1py (from versions: )
No matching distribution found for TM1py"

The problem appears unable to connect to something, log looks different from the sample.

Do I missing any step? Thanks so much for helping.
 
![Pip install TM1py error](https://user-images.githubusercontent.com/42755205/61334286-a5ef1c00-a7de-11e9-9da8-cc99a22e2659.PNG)

**Comment by MariusWirtz** [comment]
looks like you have python 2.7 installed.

If run 
`python --version`
in the anaconda prompt what does it show you ?

**Comment by slu18** [comment]
Hi, Marius, 3.7.3.  It appears that I can not connect to installation source, my company has lots of firewall, I will try using my home internet, let you know, thanks so much for getting back to me from your busy schedule!




    On ‎Wednesday‎, ‎July‎ ‎17‎, ‎2019‎ ‎12‎:‎24‎:‎34‎ ‎PM‎ ‎PDT, Marius Wirtz <notifications@github.com> wrote:  
 
 
looks like you have python 2.7 installed.

If run
python --version
in the anaconda prompt what does it show you ?

**Comment by slu18** [comment]
Hi Marius, I installed successfully at home, see below, but no luck to 'connect to tm1' via check.py in sample master yet.
thanks again, you can close my issue.




    On ‎Wednesday‎, ‎July‎ ‎17‎, ‎2019‎ ‎01‎:‎18‎:‎08‎ ‎PM‎ ‎PDT, Shirley Lu <sxlu2002@yahoo.com> wrote:  
 
  Hi, Marius, 3.7.3.  It appears that I can not connect to installation source, my company has lots of firewall, I will try using my home internet, let you know, thanks so much for getting back to me from your busy schedule!




    On ‎Wednesday‎, ‎July‎ ‎17‎, ‎2019‎ ‎12‎:‎24‎:‎34‎ ‎PM‎ ‎PDT, Marius Wirtz <notifications@github.com> wrote:  
 
 
looks like you have python 2.7 installed.

If run
python --version
in the anaconda prompt what does it show you ?

**Comment by slu18** [comment]
Hi Marius,
it is working now, I am very excited to start learning tm1py (start with your samples).  I am sorry for the mistake and thank you so much for your time. You can close the issue now


have a great weekend
Shirley


    On ‎Thursday‎, ‎July‎ ‎18‎, ‎2019‎ ‎12‎:‎52‎:‎06‎ ‎PM‎ ‎PDT, Marius Wirtz <notifications@github.com> wrote:  
 
 
Closed #56.
