### ISSUE TITLE
Check.PY Failed For Planning Sample 

### ISSUE THREAD

**Issue by slu18** [cubewise-code/tm1py-samples#57]
I follow the instruction, unable to connect to TM1 using Anaconda Prompt, I fill in user name as Admin, password empty or Apple, I definitely do not have CAM set up for it, port number or server name confirmed correct using POST, rest API query.  Not sure why target machine actively refuses it, and what I did wrong.  I did try the right click check.py folder with shift, one time I got powershell window up, it does not recognize python as a cmdlet.

![API Enabled Planning Sample](https://user-images.githubusercontent.com/42755205/61492423-18d6cf00-a966-11e9-8ba3-1535cfd5451e.PNG)

![TM1py Check Connection Error](https://user-images.githubusercontent.com/42755205/61492208-b7166500-a965-11e9-9359-b89c2cc35de7.PNG)

**Comment by MariusWirtz** [comment]
when you leave address empty TM1py will assume you are connecting to localhost.

Are you running the script on the same machine as the TM1 server ?

**Comment by slu18** [comment]
Hi Marius, not the same machine, I run in my laptop,not server.  I will enter server name and try again today, you are correct about local host issue.
Shirley 


Sent from Yahoo Mail for iPhone


On Thursday, July 18, 2019, 10:49 PM, Marius Wirtz <notifications@github.com> wrote:


when you leave address empty TM1py will assume you are connecting to localhost.

Are you running the script on the same machine as the TM1 server ?
