### ISSUE TITLE
Issue connecting to AWS ( cubike_data_science)

### ISSUE THREAD

**Issue by JDLovering** [cubewise-code/tm1py-samples#58]
![image](https://user-images.githubusercontent.com/39148628/61608367-02da4e80-ac85-11e9-9fda-c5581e201f7b.png)
![image](https://user-images.githubusercontent.com/39148628/61608512-901da300-ac85-11e9-934f-f651a57f5366.png)

I don't seem to be able to connect to the TM1 server in the example "cubike_data_science".

**Comment by MariusWirtz** [comment]
Hi @JDLovering ,

we do not provide hosted TM1 instances for the samples. You need to adjust these config parameters and run the sample against your own TM1 instance.
Before you do that make sure you run the `setup_sample.py` script against your instance.
