### ISSUE TITLE
Error with connecting to TM1Service

### ISSUE THREAD

**Issue by JDLovering** [cubewise-code/tm1py-samples#60]
Hi Again,

I'm having trouble connecting to the TM1Service with my local TM1 sever.
I was able to connect with the check.py (Script in Jupyter Notebook) as seen below in screenshot.
However when trying to connect to run Samples_Setup.py (Script in Jupyter Notebook)  the error occurs as in below screenshots

![JDLove Err3](https://user-images.githubusercontent.com/39148628/61990656-7d391300-b077-11e9-929e-b8895fb5e5dd.PNG)

![JDLove Err2](https://user-images.githubusercontent.com/39148628/61990655-7b6f4f80-b077-11e9-9489-bee7ab18cc27.PNG)

![JDLove Err1](https://user-images.githubusercontent.com/39148628/61990687-02bcc300-b078-11e9-8ca3-bf2494004768.PNG)

James

**Comment by MariusWirtz** [comment]
Hi,

this message you get when the b64decoding of the password fails.

Probably the provided password is not b64 encoded, but you provide the decode_b64 argument as True, so TM1py will try to decode it.

**Comment by JDLovering** [comment]
Hi 

Great, I have the samples added to the server now, very cool.
I changed the setting in my server config file.

Thanks
James
