### ISSUE TITLE
Processes run in parallel sample

### ISSUE THREAD

**Issue by jbeanz23** [cubewise-code/tm1py-samples#62]
Hello
I see a flag on the "processes run in parallel.py" highlighting "await" and has the following message:
Is there something missing?  Will this still be able to run?

![await](https://user-images.githubusercontent.com/8358847/62344094-7f4d0880-b4a1-11e9-83d7-3a05d354f59e.png)

**Comment by MariusWirtz** [comment]
Hi @jbeanz23,

it seems PyCharm is a bit overly sensitive here..Normally, in my experience, the things that PyCharm finds and highlights are actual issues or bad practices, but in this case it's not a thing.

Apart from the inspection, the parallelization in this script is not very elegant. In this sample we are not making use of the response in the future. So we are not checking if the process ran successfully or not.
This is managed more elengantly in RushTI.

Cheers,

Marius
