### ISSUE TITLE
Is TM1py supports PAX (Planning Analytics For Excel)

### ISSUE THREAD

**Issue by Rnvksm** [cubewise-code/tm1py-samples#63]
Hi Marius,

I want to connect PAX using Tm1py is it possible.
if please share some examples .

Thanks & Regards,
Ram Kumar

**Comment by MariusWirtz** [comment]
Hi,

TM1py wrapps the TM1 (Server) REST API. It allows you to communicate with the TM1 Server from python. You can not use TM1py to speak with PAX.

However there are good python libraries for excel integration like xlwings, openpyxl or koala. Maybe you can go down this path.

Cheers,

Marius
