### ISSUE TITLE
Issue installing TM1py

### ISSUE THREAD

**Issue by Ank888** [cubewise-code/tm1py-samples#68]
I am new to Python, and I am trying to install TM1py in Python 3.7. Here is an error "Could not find a version that satisfies the requirement pywin32". I ran "pip install TM1py" in Command Prompt, and it worked, but I cannot access the package in PyCharm, getting an error "ModuleNotFoundError: No module named 'TM1py'". When I attempt to install in Project Interpreter, I have a problem with the installation itself.

The complete output:

Collecting TM1py
Using cached https://files.pythonhosted.org/packages/66/d9/268ed93d5bddbc59d41f4c35af89c34534addd6fc33b56d7eef0402998cb/TM1py-1.4.1.tar.gz
Collecting requests (from TM1py)
Using cached https://files.pythonhosted.org/packages/1a/70/1935c770cb3be6e3a8b78ced23d7e0f3b187f5cbfab4749523ed65d7c9b1/requests-2.23.0-py2.py3-none-any.whl
Collecting pandas (from TM1py)
Using cached https://files.pythonhosted.org/packages/2f/79/f236ab1cfde94bac03d7b58f3f2ab0b1cc71d6a8bda3b25ce370a9fe4ab1/pandas-1.0.3.tar.gz
Installing build dependencies: started
Installing build dependencies: still running...
Installing build dependencies: finished with status 'done'
Getting requirements to build wheel: started
Getting requirements to build wheel: still running...
Getting requirements to build wheel: still running...
Getting requirements to build wheel: finished with status 'done'
Preparing wheel metadata: started
Preparing wheel metadata: finished with status 'done'
Collecting pytz (from TM1py)
Using cached https://files.pythonhosted.org/packages/e7/f9/f0b53f88060247251bf481fa6ea62cd0d25bf1b11a87888e53ce5b7c8ad2/pytz-2019.3-py2.py3-none-any.whl
Collecting requests_negotiate_sspi (from TM1py)
Using cached https://files.pythonhosted.org/packages/7c/0b/99220cb4d3c8cf9b667a1cd13650d28b19e689ab7145085897e254d141a3/requests_negotiate_sspi-0.5.2-py2.py3-none-any.whl
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests->TM1py)
Using cached https://files.pythonhosted.org/packages/e8/74/6e4f91745020f967d09332bb2b8b9b10090957334692eb88ea4afe91b77f/urllib3-1.25.8-py2.py3-none-any.whl
Collecting chardet<4,>=3.0.2 (from requests->TM1py)
Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->TM1py)
Using cached https://files.pythonhosted.org/packages/b9/63/df50cac98ea0d5b006c55a399c3bf1db9da7b5a24de7890bc9cfd5dd9e99/certifi-2019.11.28-py2.py3-none-any.whl
Collecting idna<3,>=2.5 (from requests->TM1py)
Using cached https://files.pythonhosted.org/packages/89/e3/afebe61c546d18fb1709a61bee788254b40e736cff7271c7de5de2dc4128/idna-2.9-py2.py3-none-any.whl
Collecting numpy>=1.13.3 (from pandas->TM1py)
Using cached https://files.pythonhosted.org/packages/84/1e/ff467ac56bfeaea51d4a2e72d315c1fe440b20192fea7e460f0f248acac8/numpy-1.18.2.zip
Installing build dependencies: started
Installing build dependencies: finished with status 'done'
Getting requirements to build wheel: started
Getting requirements to build wheel: finished with status 'done'
Preparing wheel metadata: started
Preparing wheel metadata: finished with status 'done'
Collecting python-dateutil>=2.6.1 (from pandas->TM1py)
Using cached https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl
Collecting pypiwin32>=223 (from requests_negotiate_sspi->TM1py)
Using cached https://files.pythonhosted.org/packages/d0/1b/2f292bbd742e369a100c91faa0483172cd91a1a422a6692055ac920946c5/pypiwin32-223-py3-none-any.whl
Collecting six>=1.5 (from python-dateutil>=2.6.1->pandas->TM1py)
Using cached https://files.pythonhosted.org/packages/65/eb/1f97cb97bfc2390a276969c6fae16075da282f5058082d4cb10c6c5c1dba/six-1.14.0-py2.py3-none-any.whl
Collecting pywin32>=223 (from pypiwin32>=223->requests_negotiate_sspi->TM1py)

Could not find a version that satisfies the requirement pywin32>=223 (from pypiwin32>=223->requests_negotiate_sspi->TM1py) (from versions: )
No matching distribution found for pywin32>=223 (from pypiwin32>=223->requests_negotiate_sspi->TM1py)

**Comment by MariusWirtz** [comment]
Hi @Ank888,

this is strange. I have not seen this error.
Are you using windows os?

The error 
```
Could not find a version that satisfies the requirement pywin32>=223 (...)
No matching distribution found for pywin32>=223
```
indicates that the pywin32 package is not available for your setup (TM1py needs this package to do single sign on). 
Could it be that you are using an older Python version? - Or perhaps you have to versions of python on your PC and pip is using the old one?
You can check by running:
`python --version`

**Comment by Ank888** [comment]
Hi MariusWirtz,
Yes, I am using Windows 10.  The first error during the installation was the requirement of installing Visual C++, which I did.  Can it be that I am missing some other required software?  I have only one version of Python, and it's 3.7.
Also, one of my co-workers attempted to install TM1py, he has Python 3.5, and he received the same error message.

**Comment by Ank888** [comment]
Also, if I type "python --version" in CDM, I don't get anything, but Python is on my box, I can open PyCharm and use other packages.

**Comment by MariusWirtz** [comment]
Hi @Ank888 ,
if you haven't added python to the windows path, you can execute the `python --version` statement in the python install directory (e.g.  `C:\Python3`). 

apparently pypiwin32 seems the be the predecessor of pywin32 
https://stackoverflow.com/questions/55918311/what-is-the-difference-between-pywin32-and-pypiwin32
You do need pywin32. 

In the log statements above it looks like you are using python38. 
Can you please install python37 and try it again? We still do all our testing against python37. Normally that should not be an issue, but I believe 3.8 is still rather new.

Cheers,

Marius

**Comment by Ank888** [comment]
Looks like it works with Python 3.7.7, but not with 3.8 version.  It was confusing with 3.8 since it was still showing 3.7 for 64 bit installation.  Anyway, it seems to work after the reinstall.  Thank you.
