### ISSUE TITLE
Create a TM1 dimension directly from sharepoint using TM1PY

### ISSUE THREAD

**Issue by asmaa-mel** [cubewise-code/tm1py-samples#70]
Hello, 
I need to collect data from SharePoint and based on these data, I have to create/ update a dimension on TM1.
Is this doable using TM1PY? 
Thanks in advance

**Comment by MariusWirtz** [comment]
Hello @asmaa-mel,

I haven't done this myself, but I am confident that it can be accomplished with little effort.
So essentially you need to do three things:

1. Access the page on SharePoint with python. Authentication might be a [challenge](https://stackoverflow.com/questions/20945822/how-to-access-a-sharepoint-site-via-the-rest-api-in-python), the rest should be simple. You could use the requests library to request information from the SharePoint page.

2. Build/update a TM1py dimension object from the data that you retrieved. You can find a sample on how to build a dimension [here](https://github.com/cubewise-code/tm1py-samples/blob/master/Metadata/dim_create.py).

3. Create or update the dimension in your TM1 instance with TM1py. Use the `tm1.dimensions.update` or `tm1.dimensions.create` method.

I can't help you with point 1, but if you get stuck with 2. or 3. feel free to post something here.

**Comment by asmaa-mel** [comment]
Hello @MariusWirtz 
thanks for your quick feedback, I'll definitely revert if I need more assistance
