### ISSUE TITLE
Time Out Connecting to server

### ISSUE THREAD

**Issue by dpeeroo** [cubewise-code/tm1py-samples#75]
Hi Marius

We really enjoyed the TM1 Horizon event, and congratulation to all of you on a brilliant event. Sorry to bother you with this, im hoping its me being a wally! 
So I thought i'd have a play with some of the stuff you showed us, but I cant even get past the connection. Check.py seems to say I have a connection and the correct vars are in the tm1s.cfg.  But when I try to connect to the Tm1Service, it simply hangs and doesnt complete (Fig 1):
![TM1py connection hang](https://user-images.githubusercontent.com/70566005/91813090-0bdc7400-ec2a-11ea-969e-ffc58c3b3d9a.PNG)

I have upgraded to the latest tm1py and have python 37 on the dev box so I think ive installed the right bits. 
I cant find any error logs to help me, Is there a different log for tm1py, in a different location to tm1 server logs? 

Do you have any ideas?

Many thanks in advance

Dan

P.S Tm1 version is PA 2.0.7

**Comment by dpeeroo** [comment]
Managed to fix this. I'd put in wrong syntax. Should have been:
![image](https://user-images.githubusercontent.com/70566005/91823329-f4ed5000-ec30-11ea-844e-230e80a9a646.png)
Sorry to waste your time there

**Comment by MariusWirtz** [comment]
Hi @dpeeroo,
happy to hear that it works now and thanks for the great feedback on the tm1 horizon conference!
