### ISSUE TITLE
No Data and errors

### ISSUE THREAD

**Issue by dpeeroo** [cubewise-code/tm1py-samples#76]
Hi Marius

Sorry to bother you again but Ive hit a roadblock. 

Firstly when trying to access the Trans Log in Tm1 Im getting nothing returned. I should have 4 records being returned but I see [] :
![image](https://user-images.githubusercontent.com/70566005/91854207-4ad6ed80-ec5b-11ea-96bf-69349aaf8633.png)
In the Trans Log I have the 4 records:
![image](https://user-images.githubusercontent.com/70566005/91854780-262f4580-ec5c-11ea-834e-35448daf2ec7.png)

So instead I tried another example , the one that returns data from a cube view:
![image](https://user-images.githubusercontent.com/70566005/91854869-48c15e80-ec5c-11ea-954a-baa1c9de1b73.png)
But I get this error:
![image](https://user-images.githubusercontent.com/70566005/91854976-6f7f9500-ec5c-11ea-909d-ec59ad4d3339.png)

Am I doing something wrong? Ive tried lots of things but its hard to work out as ive not used any of this before. Any pointers would be great

Thanks Again

Dan

**Comment by MariusWirtz** [comment]
Hi @dpeeroo,

the user name and cube name filters on the transaction log are case sensitive in the REST API. So you have to write DPeeroo.
It doesn't make sense IMO, but that's how IBM built it in the API.

To solve the second problem you can do 2 things:
- Upgrade to the latest TM1py master branch here on GitHub with pip: `pip install https://github.com/cubewise-code/tm1py/archive/master.zip --upgrade`
- add the third argument private=False to the function call

I hope this helps!

**Comment by dpeeroo** [comment]
Hi Marius 

This is great! Its working now and I have data so I can go through the Challenges you did in your demo.

Many many thanks again

Dan

**Comment by MariusWirtz** [comment]
You are welcome!

PS
to know what arguments a function requires (e.g. `cube_name`, `view_name`, `private`) you can press shift + tab when the cursor is inside the parenthesis
