### ISSUE TITLE
Single Login to Execute Multiple TIs

### ISSUE THREAD

**Issue by kool2zero** [cubewise-code/TM1py-samples#8]
I've seen Quebit use the Rest API to perform a single login while executing multiple TIs simultaneously.  Is that possible with TM1py?  I've tried looking at the code and modifying it a bit but I'm new at Python and REST.  I was only able to get it to log in once for each process.  Sometimes with CAM we see locking while executing multiple processes in RunTI and I was thinking REST would be a way to fix that.

**Comment by MariusWirtz** [comment]
Hi,

yeah you can do this. Check out this sample:
https://github.com/cubewise-code/TM1py-samples/blob/master/Other/run%20TI%20Processes%20in%20parallel.py

**Comment by kool2zero** [comment]
I tried that but it still seemed to log in multiple times according to the contention log.

**Comment by MariusWirtz** [comment]
Hi,
it does login multiple times, but the authentification (with CAM) is done only for the first Request.
Then TM1py reuses the session.

**Comment by MariusWirtz** [comment]
For now there is no way to execute multiple processes asynchronously from one request (one login) through the REST API.
https://www.ibm.com/developerworks/community/forums/html/topic?id=b8a24fac-eb82-4ebd-9d33-cba3ba568310
