### ISSUE TITLE
Creating a subset with Level 0 elements only 

### ISSUE THREAD

**Issue by jace112233** [cubewise-code/tm1py-samples#81]
Hi All, 

I would like to ask if is possible to create subset with only level 0 elements in tm1py?

**Comment by MariusWirtz** [comment]
Sure. Here you go:

``` python
from TM1py import TM1Service, Subset

with TM1Service(user='admin', password='apple', address='', port=12354, ssl=True) as tm1:
    subset = Subset(
        subset_name="All States",
        dimension_name="State",
        hierarchy_name="State",
        expression='{Tm1FilterByLevel({Tm1SubsetAll( [State] )},0)}')
    tm1.subsets.update_or_create(subset, private=False)

```

**Comment by jace112233** [comment]
> ```python
>     subset = Subset(
>         subset_name="All States",
>         dimension_name="State",
>         hierarchy_name="State",
>         expression='{Tm1FilterByLevel({Tm1SubsetAll( [State] )},0)}')
>     tm1.subsets.update_or_create(subset, private=False)
> ```
