### ISSUE TITLE
Chore Rescheduling issue

### ISSUE THREAD

**Issue by Rnvksm** [cubewise-code/tm1py-samples#82]
Hi MariusWirtz,

This to inform  facing issue with rescheduling chore. While rescheduling active chores  its deactivating the chore and updated the time then reactivating this steps are happening (Checked my log) and chore timestamp also updated in data folder. but some how the chore is not executing after successfully updated the chore details.
Doubt: is Chore required restart?

regards,
Ram Kumar

**Comment by MariusWirtz** [comment]
Hi @Rnvksm,

what version of the TM1 Server are you using?
Use this code to find out:

```python
from TM1py import TM1Service

with TM1Service(address='localhost', port=50501, user='Admin', password='apple', ssl=True) as tm1:
    print(tm1.version)

```

**Comment by Rnvksm** [comment]
Hi Marius,
 
Ran the above query got this info 11.8.00000.33 ( Planning Analytics 2.0.9.1)
Today restarted my instance after that my chore got executed as per reschedule.
As per my knowledge chore doesn't require restart right  but some how reschedule functionality(TM1py) is working after restart.

**Comment by MariusWirtz** [comment]
Hi @Rnvksm,

thank you.
This is interesting. If it only works after a restart, it sounds like an issue in the TM1 Server to me.

Perhaps to work around the issue, you can delete the chore and recreate it instead of updating it.

**Comment by Rnvksm** [comment]
Thanks @MariusWirtz  for quick reply.
 
I tried with save data after rescheduling chore. still that's not working. i made a utility called Chore automation Dashboard there i added all functionalities related with chores except reschedule everything is working fine.

**Comment by MariusWirtz** [comment]
Interesting. 

If you reschedule the chore like this, do you still have to restart the server?

``` python
from TM1py import TM1Service

with TM1Service(address="", port=12354, ssl=True, user="admin", password="apple") as tm1:
    chore = tm1.chores.get(chore_name="1400_DailyProcessing")

    chore.reschedule(hours=-1)

    tm1.chores.delete(chore_name=chore.name)
    tm1.chores.create(chore=chore)

```

**Comment by Rnvksm** [comment]
Thanks @MariusWirtz 

Sure. i will try and will let you know the result.

Regards,
Ram Kumar

**Comment by Rnvksm** [comment]
Hi @MariusWirtz ,

I tried the above code still chore is not  executing by chore scheduler. i think it need restart.
Thats the only option working for reschedule  the chore.

**Comment by MariusWirtz** [comment]
Thank you for the confirmation.

I will reproduce the issue on my site and report it with IBM.

**Comment by Rnvksm** [comment]
Thanks Marius,

If you find any solution please let me know
