### ISSUE TITLE
TM1py Time Series Forecasting Question

### ISSUE THREAD

**Issue by slu18** [cubewise-code/tm1py-samples#85]
Hi Marius,  I got the sample Jupyter Notebook, just wondering how to get the retail cube and time series view to learn how TM1py works by running the codes in the sample.  If retail cube does not exist in any of the sample database with TM1 installation, I can create it myself, just want to know whether there is another tm1py example that creates this cube and view, there are many examples in master sample folder, thank you

**Comment by MariusWirtz** [comment]
Hi @slu18,

sorry for the extremely late reply. for the time series forecasting use case, I recommend you check out the `Cubike` sample.
we provide a help article and a script to set up your environment with all required dimensions and cubes.
https://github.com/cubewise-code/tm1py-samples/tree/master/Samples/Cubike
https://code.cubewise.com/blog/data-science-with-tm1-planning-analytics

Cheers

Marius
