### ISSUE TITLE
Issues with Login

### ISSUE THREAD

**Issue by vpkumarbi** [cubewise-code/TM1py-samples#9]
I have two issues.

1. On my tm1 host server i have two tm1 instances? How do i mention that i can only login to particular server?

2. I have my tm1 single signon implemented with bi. In this case how do I provide credentials? Domain\Username? or the Client name in the client groups cube?

Please see below screenshot.

![image](https://user-images.githubusercontent.com/3416001/30410995-ff6a29c6-98d3-11e7-8862-7836f123eebf.png)

**Comment by MariusWirtz** [comment]
Regarding 1, through the address and the port number you are addressing a TM1 instance unambiguously.
If you don't want to login to the second tm1 instance, just don't do it.
Or are you saying you want to prevent other users from accessing the second instance through the REST API?

The check.py script is hard coded to native TM1 login. We should probably mention this in the comments! Sorry for that.
If you want to connect to a TM1 instance through CAM you need to pass the CAM Namespace as an argument when instantiating the TM1Service. The user/ client name can be specified as it is in the }Clients dimension:

```
from TM1py.Services import TM1Service

# Connect to TM1
with TM1Service(address='localhost', port=8001, namespace='HarmonyLDAP', user='admin', password='apple', ssl=True) as tm1:
    parameters = {
        'Parameters': [{
            'Name': "pWaitSec",
            'Value': "10"
        }]
    }
    tm1.processes.execute('Bedrock.Server.Wait', parameters)

```

**Comment by vpkumarbi** [comment]
For Issue 1, I changed the port numbers and worked for me.
For Issue 2, I provided the namespace and worked for me.
Thanks!
