### ISSUE TITLE
No response from URL; despite validating URL and Port

### ISSUE THREAD

**Issue by StreetRodRacer** [cubewise-code/tm1py-samples#91]
Good Afternoon,

I have downloaded TM1Py, tested the check.py script and returned the correct version number. I then started exploring with a few sample scripts:

```
from TM1py import TM1Service

with TM1Service(address='localhost', port=8001, ssl=True, user='user', password='apple') as tm1:
    dataframe = tm1.cells.execute_view_dataframe_shaped(cube_name='CUBE', view_name='VIEW')
    
    dataframe.head ()
    dataframe.to_excel("test.xlsx")
```

However, I receive a error message which read, "No response from URL. Please double-check the URL and Port number. The URL is the same as the one that I successfully used in the check.py script and the Port Number was pulled from the TM1.cfg file. The environment is hosted on IBM Cloud, so I am not sure if that impacts the script?

Any help would be greatly appreciated.

Thank you!

**Comment by Rnvksm** [comment]
Hi @StreetRodRacer ,

Please try this way
---------------------
    from TM1py import TM1Service

    with TM1Service(address='localhost', port=8001, ssl=True, user='user', password='apple') as tm1:
        dataframe = tm1.cells.execute_view_dataframe_shaped(cube_name='Currency Exchange Rates', view_name='Default',private=False)
    
        print(dataframe.head())
        dataframe.to_excel("test.xlsx")

    print(dataframe.head())
    dataframe.to_excel("test.xlsx")
