### ISSUE TITLE
Change Creator for Annotations

### ISSUE THREAD

**Issue by dmillerksu** [cubewise-code/tm1py-samples#92]
I don't seem to be able to specify a creator when writing an annotation from TM1py.  

We have a commentary cube for our P&L cube.  We're writing a script to pull the commentary from that cube and write it as an actual annotation in the P&L cube.  

I have the script pulling the data, deleting existing annotations in the target, and writing the new annotation.  I can specify the creator in the Annotation object, but when I create the annotation, it still sets the creator as whatever user is associated with the TM1py scripts TM1Service connection.  

Is there a way to force the comment's creator?  (without having them provide their credentials)

Thanks,
Danny

**Comment by MariusWirtz** [comment]
Perhaps you can use impersonation when you write the annotation back.
Would that solve your problem?

**Comment by dmillerksu** [comment]
Didn't realize this was available.  Impersonate did solve the problem.  Although we can't use this if the user making a comment is an admin, but I think we can get around this.  Thanks for the help!
