### ISSUE TITLE
Trying to find out the  top parent of an Element in Dimension using TM1py

### ISSUE THREAD

**Issue by Rnvksm** [cubewise-code/tm1py-samples#93]
have created the MDX for that but need help to execute and get the value and have tried multiple ways but no luck.
Please help me ASAP

Script:
        hieset=MdxHierarchySet.ancestors(Member.of(dim, '1110')).tail(1)

        md=hieset.to_mdx()

**Comment by MariusWirtz** [comment]
solved with https://github.com/cubewise-code/tm1py/issues/825
