### ISSUE TITLE
Need Py to pull data out of Transaction Logs

### ISSUE THREAD

**Issue by CJRothman** [cubewise-code/tm1py-samples#94]
I downloaded transactionlog_entries_since_timestamp.py from the Samples library but it just has a bunch of HTML code. I don't see the Python script. Where can I get some script to pull transaction log entries and load it into a cube?
https://github.com/cubewise-code/tm1py-samples/blob/master/Administration/transactionlog_entries_since_timestamp.py

**Comment by MariusWirtz** [comment]
here you go:

``` python
"""
Get all TM1 transactions for all cubes starting to a specific date.
"""

import configparser
from datetime import datetime

from TM1py.Services import TM1Service

config = configparser.ConfigParser()
# storing the credentials in a file is not recommended for purposes other than testing.
# it's better to setup CAM with SSO or use keyring to store credentials in the windows credential manager. Sample:
# Samples/credentials_best_practice.py
config.read(r'..\config.ini')

with TM1Service(**config['tm1srv01']) as tm1:
    # Timestamp for Message-Log parsing
    timestamp = datetime(year=2018, month=2, day=15, hour=16, minute=2, second=0)

    # Get all entries since timestamp
    entries = tm1.server.get_transaction_log_entries(since=timestamp)

    # loop through entries
    for entry in entries:
        # Do stuff
        print(entry['TimeStamp'], entry)
```

Please note that in TM1 11 querying the transactionlog required rigid management of the cube transaction logging.
It will not work, or produce locks, if your instance has tm1s files with millions of records.

**Comment by CJRothman** [comment]
Thanks Marius. I took your code and customized it to look for changes to cubes in a cube list, however, I am only able to loop through a cube list (which would probably make it slower as it would have to load the transaction log multiple times). 
    CubeList = ["Exchange Rates", "Store Sales Plan", "Gross Margin Calculation", "Base Sales Forecast"]
    for Cube in CubeList:
        # Get all entries for each cube in list since timestamp
        entries = tm1.server.get_transaction_log_entries(since=timestamp, cube=Cube)

I tried logic like this but it didn't work (SyntaxError: positional argument follows keyword argument). Interested in your thoughts.
    CubeList = ["Exchange Rates", "Store Sales Plan", "Gross Margin Calculation", "Base Sales Forecast"]
    # Get all entries for each cube in list since timestamp
    entries = tm1.server.get_transaction_log_entries(since=timestamp, cube **in CubeList**)
