### ISSUE TITLE
TM1py.Exceptions.Exceptions.TM1pyRestException: Text: Status Code:404 Reason: 'Not Found

### ISSUE THREAD

**Issue by Ajitvera** [cubewise-code/tm1py-samples#96]
Hi Team,

I was trying to load data from csv to cube, i have used the same code which we have on this link https://github.com/cubewise-code/tm1py-samples/tree/master/Data
<img width="698" alt="Code" src="https://github.com/cubewise-code/tm1py-samples/assets/156689926/5a899e7d-c684-4ee7-b69c-7613487f24ef">

When i ran the code i got the error that one of element is not found but element is already added in the dimension.
Please find the screenshot of error as well
<img width="959" alt="Error" src="https://github.com/cubewise-code/tm1py-samples/assets/156689926/c16a7faa-e9c2-4f7a-99b4-728b108ea83a">
 it is saying FY 2003 Budget can not be found in collection of type Element and error Status code is 404.

Can you please guide me what i am doing wrong here.
Thanks:-
Ajit Kumar

**Comment by MariusWirtz** [comment]
This repository is not actively maintained. 
Please ask questions over at the TM1py repo: https://github.com/cubewise-code/tm1py/discussions

Regarding your error message it says: "'FY 2003 Budget' can not be found". 
Is it possible that you don't have this element in the dimension? Or perhaps the element order doesn't match the dimension order of the cube in TM1?
